# Generated by Django 3.1.4 on 2020-12-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201229_1908'),
        ('blog', '0002_auto_20201229_2246'),
    ]

    operations = [
    ]
